baseURL = 'https://xsro.github.io/event20250521/'
languageCode = 'en-us'
title = 'Zhang Fan @ SYSUsz'
theme= "hugo-academia"
canonifyURLs = true # if use absolute path.

[params]
author = "Dr. Zhang Fan"
author_bio = ""
since = "2018"
icp = ""
avatar = "/images/张凡.jpg"
favicon = "/images/favicon-32x32.ico"  # Please use .ico format

[params.menu]
[params.menu.Home]
    name = "Home"
    url = "/"
    weight = 1

[params.menu.About]
    name = "About"
    url = "/about/"
    weight = 2

[params.menu.Publications]
    name = "Publications"
    url = "/publication/"
    weight = 3

[params.menu.Members]
    name = "Members"
    url = "/member/"
    weight = 4

[params.menu.Event]
    name = "Workshop 2025"
    url = "events/workshop20250521"
    weight = 5

[params.loading_bg]
  flink = "/images/profile.png"

  [params.social]
  enable = true

[params.social.links.SYSU]
icon = "fas fa-university"
url = "https://saa.sysu.edu.cn/teacher/231"
weight = 1


[params.social.links.Envelope]
icon = "fas fa-envelope"
url = "mailto:drfzh@outlook.com"
weight = 2


  [params.e_social]
  enable = true

[params.e_social.links."email"]
name = "drfzh@outlook.com"
url = "mailto:drfzh@outlook.com"
icon = "fas fa-graduation-cap"
weight = 1

# CDN
# 根据需要自行添加js/css
# 自定义css可以直接写在user.styl中
[params.CDN_USE]
css = [
    "/css/style.css",
    "https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.13.0/css/all.min.css"  # fontawesome 5
]
js = [
    "https://cdn.jsdelivr.net/npm/jquery@latest/dist/jquery.min.js",  # /js/third-party/jquery.min.js
    "https://cdn.jsdelivr.net/npm/jquery-pjax@latest/jquery.pjax.min.js",
    "/js/main.js"
]


[caches]
  [caches.images]
    dir = ':cacheDir/images'